-- Merlin Agency visitor tracking (Supabase)
-- Uses the existing visitor_logs table shared with the other domain sites.

create table if not exists public.visitor_logs (
  id bigint generated by default as identity primary key,
  site text not null,
  visitor_type text not null default 'human',
  city text,
  country text,
  country_code text,
  timestamp timestamptz not null default now(),
  user_agent text,
  referrer text
);

-- Allow Merlin's site value in the shared table.
alter table public.visitor_logs drop constraint if exists visitor_logs_site_check;
alter table public.visitor_logs add constraint visitor_logs_site_check
  check (site in ('classyheels.com','mughlaifood.com','odinship.com','begrow.in'));

alter table public.visitor_logs enable row level security;

drop policy if exists "visitor_logs_insert_public" on public.visitor_logs;
create policy "visitor_logs_insert_public" on public.visitor_logs
  for insert to anon, authenticated with check (site in ('classyheels.com','mughlaifood.com','odinship.com','begrow.in'));

drop policy if exists "visitor_logs_select_public" on public.visitor_logs;
create policy "visitor_logs_select_public" on public.visitor_logs
  for select to anon, authenticated using (site in ('classyheels.com','mughlaifood.com','odinship.com','begrow.in'));

drop policy if exists "visitor_logs_delete_public" on public.visitor_logs;
create policy "visitor_logs_delete_public" on public.visitor_logs
  for delete to anon, authenticated using (site = 'begrow.in');

create index if not exists visitor_logs_site_timestamp_idx
  on public.visitor_logs(site, timestamp desc);
